"""add_nit_field_to_invoices

Revision ID: 0002_add_nit_field_to_invoices
Revises: 0001_add_ocr_fields_to_invoices
Create Date: 2025-09-30 02:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0002_add_nit_field_to_invoices'
down_revision = '0001_add_ocr_fields_to_invoices'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('nit', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_invoices_nit'), 'invoices', ['nit'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_nit'), table_name='invoices')
    op.drop_column('invoices', 'nit')
    # ### end Alembic commands ###

