"""add_gmail_attachments_field

Revision ID: 0003_add_gmail_attachments_field
Revises: 0002_add_nit_field_to_invoices
Create Date: 2025-10-05 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_add_gmail_attachments_field'
down_revision = '0002_add_nit_field_to_invoices'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('gmail_attachments', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'gmail_attachments')
    # ### end Alembic commands ###

